apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: example-service
  description: A service that does this and that
  annotations:
    github.com/project-slug: micc83/test-repository
    backstage.io/techdocs-ref: dir:.
  tags:
    - php
  links:
    - url: https://admin.example-org.com
      title: Admin Dashboard
      icon: dashboard
      type: admin-dashboard
spec:
  type: service
  lifecycle: production
  owner: guests
  dependsOn:
    - component:example-website
  providesApis:
    - custom-api
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: custom-api
  description: Retrieve pets
spec:
  type: openapi
  lifecycle: production
  owner: guests
  definition:
    $text: ./schema.yml
