# Service 1
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: my-example-service
  description: A service that does this and that
  annotations:
    github.com/project-slug: micc83/test-repository
    backstage.io/techdocs-ref: dir:.
  tags:
    - php
  links:
    - url: https://api.service-1.com
      title: Service host
      type: backend
spec:
  type: service
  lifecycle: production
  owner: guests
  providesApis:
    - custom-api
    - my-custom-async-api
---
# Service 2
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: another-example-service
  description: A service that does this and that
  tags:
    - node
    - nestjs
  links:
    - url: https://api.service-2.com
      title: Service host
      type: backend
spec:
  type: service
  lifecycle: production
  owner: guests
  consumesApis:
    - my-custom-async-api
  providesApis:
    - my-graphql-api
---
# OpenAPI from service 1
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: custom-api
  description: Retrieve pets
spec:
  type: openapi
  lifecycle: production
  owner: guests
  definition:
    $text: ./schema.yml
---
# AsyncAPI from service 1
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: my-custom-async-api
  description: RMQ messages
spec:
  type: asyncapi
  lifecycle: production
  owner: guests
  definition:
    $text: ./asyncapi.yml
---
# GraphQL API from service 2
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: my-graphql-api
  description: GraphQL API
spec:
  type: graphql
  lifecycle: production
  owner: guests
  definition:
    $text: ./schema.graphql
---
# Website consuming API from Service 1
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: my-example-website
  description: My example website
  links:
    - url: https://admin.example-org.com
      title: Admin Dashboard
      icon: dashboard
      type: admin-dashboard
spec:
  type: website
  lifecycle: production
  owner: guests
  consumesApis: 
    - custom-api
  dependsOn:
    - component:my-example-service

