# Organization
# Team Voyager
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: team-voyager
  title: Team Voyager
spec:
  type: team
  children: []
---
# Team Buktu
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: team-buktu
  title: Team Buktu
spec:
  type: team
  children: []
---
# Team BI
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: team-bi
  title: BI
spec:
  type: team
  children: []
---
# Team Devops
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: team-devops
  title: DevOps
spec:
  type: team
  children: []
---
# Service 1
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: my-example-service
  title: Service 1
  description: A service that does this and that
  annotations:
    github.com/project-slug: micc83/test-repository
    backstage.io/techdocs-ref: dir:.
  tags:
    - php
  links:
    - url: https://api.service-1.com
      title: Service host
      type: backend
spec:
  type: service
  lifecycle: production
  owner: team-voyager
  providesApis:
    - custom-api
    - my-custom-async-api
  dependsOn:
    - resource:google-big-query
---
# Service 2
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: another-example-service
  title: Service 2
  description: A service that does this and that
  tags:
    - node
    - nestjs
  links:
    - url: https://api.service-2.com
      title: Service host
      type: backend
spec:
  type: service
  lifecycle: production
  owner: team-buktu
  consumesApis:
    - my-custom-async-api
  providesApis:
    - my-graphql-api
---
# OpenAPI from service 1
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: custom-api
  title: Service 1 REST API
  description: Retrieve pets
spec:
  type: openapi
  lifecycle: production
  owner: team-voyager
  definition:
    $text: ./schema.yml
---
# AsyncAPI from service 1
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: my-custom-async-api
  title: Service 1 AsyncAPI
  description: RMQ messages
spec:
  type: asyncapi
  lifecycle: production
  owner: team-voyager
  definition:
    $text: ./asyncapi.yml
---
# GraphQL API from service 2
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: my-graphql-api
  title: Service 2 GraphQL API
  description: GraphQL API
spec:
  type: graphql
  lifecycle: production
  owner: team-buktu
  definition:
    $text: ./schema.graphql
---
# Website consuming API from Service 1
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: my-example-website
  title: Service 1 Admin panel
  description: My example website
  links:
    - url: https://admin.example-org.com
      title: Admin Dashboard
      icon: dashboard
      type: admin-dashboard
spec:
  type: website
  lifecycle: production
  owner: team-voyager
  consumesApis: 
    - custom-api
  dependsOn:
    - component:my-example-service
---
# BigQuery
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: google-big-query
  title: Google BigQuery
  description: Stores BIG DATA
spec:
  type: database
  owner: team-bi
---
# BigQuery
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: postgresql
  title: PostgreSQL
  description: Stores all databases
spec:
  type: database
  owner: team-devops
